### ISSUE TITLE
unused argument (repos = repos)

### ISSUE THREAD

**Issue by florianorgeret** [r-suzuki/dateback#9]
Hello, many thanks for your work!

I am trying to make a old script  to rerun on R3.2.1 by installing packages used in 2015-06-18

But running the followings give some Errors

`dateback::install(pkgs = "ggplot2", date="2015-06-18")`

> Error in utils::available.packages(repos = repos, type = "source") : 
>   unused argument (repos = repos)
> Error in dateback::install(pkgs = "ggplot2", date = "2015-06-18") : 
>   An error occured during dateback::collect()
> Downloaded contents are in:
> 	/tmp/RtmpaT59EC/dateback/downloaded_packages

And then
`dateback::collect(pkgs = "ggplot2", date="2015-06-18", outdir = "pkgs", overwrite = T)`

> Error in utils::available.packages(repos = repos, type = "source") : 
>   unused argument (repos = repos)

`sessionInfo()`

> R version 3.2.1 (2015-06-18)
> Platform: x86_64-unknown-linux-gnu (64-bit)
> Running under: Pop!_OS 20.04 LTS
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] tools_3.2.1    dateback_1.0.4 renv_1.0.5

**Comment by r-suzuki** [comment]
Thanks for your report. I've tried to fix some compatibility issues with older R versions.

It would be helpful if you could try this version: [dateback_1.0.4-999.tar.gz](https://github.com/r-suzuki/dateback/files/14941529/dateback_1.0.4-999.tar.gz)

The following code worked fine with R-3.2.1 on Windows. I needed to change repos to HTTP mirror since HTTPS mirror did not work (it may not be needed on Linux or other OSes).
```r
dateback::collect(pkgs = "ggplot2", date = "2015-06-18", outdir = "outdir", repos = "http://lib.stat.cmu.edu/R/CRAN")
```

As an alternative way, you can `dateback::collect` packages on newer R and then install them with R-3.2.1. Please see the "Examples" section of `?dateback::collect` for details.

**Comment by florianorgeret** [comment]
Thank you very much, 
it worked with [dateback_1.0.4-999.tar.gz](https://github.com/r-suzuki/dateback/files/14941529/dateback_1.0.4-999.tar.gz)
and 
`dateback::collect(pkgs = "ggplot2", date = "2015-06-18", outdir = "outdir", repos = "http://lib.stat.cmu.edu/R/CRAN")`

but the install function is still not working (I am not sure to understand about build tools ready for my system?)
`dateback::install("ggplot2", date="2015-06-18")`
> https:// URLs are not supported by the default method: trying "libcurl"
> Warning messages:
> 1: invalid input found on input connection 'https://cloud.r-project.org/web/packages/available_packages_by_date.html' 
> 2: In readLines(con) :
>   incomplete final line found on 'https://cloud.r-project.org/web/packages/available_packages_by_date.html'
> 3: package ‘ggplot2’ is not available (for R version 3.2.1)

May I ask you how would you then install all downloaded packages at once in "outdir"?

Many thanks again for the great work!

**Comment by r-suzuki** [comment]
Thank you for trying it out. Roughly speaking, `dateback::install` is a combination of `dateback::collect` and `install.packages`. This problem seems to be occuring during the `dateback::collect` step, and it will be resolved if you specify an HTTP mirror:

```r
dateback::install("ggplot2", date = "2015-06-18", repos = "http://lib.stat.cmu.edu/R/CRAN")
```

At this point it would also be nice to set `outdir` argument, like you did with `dateback::collect`:

```r
dateback::install("ggplot2", date = "2015-06-18", outdir = "local_repo", repos = "http://lib.stat.cmu.edu/R/CRAN")
```

It creates a directory `local_repo`. If the installation failed, typically you may need to install some other software (like `libcurl` for example). After that, you no longer need to collect the source of R packages again. Instead you can try re-installing them with:

```r
install.packages(pkgs = "ggplot2", repos = "file:local_repo")
```

Please see the Examples section of `?dateback::collect`.

**Comment by florianorgeret** [comment]
Many thanks! Sorry for the late reply, but all worked!

**Comment by r-suzuki** [comment]
Great! The changes will be included in the next release. Thank you for your feedback!
